-- MySQL Script generated by MySQL Workbench
-- Sun Mar 14 20:31:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema job_search_engine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema job_search_engine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `job_search_engine`;
USE
`job_search_engine` ;

-- -----------------------------------------------------
-- Table `job_search_engine`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`role`
(
    `id` BIGINT
(
    100
) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR
(
    255
) NOT NULL,
    PRIMARY KEY
(
    `id`
)
    );

-- -----------------------------------------------------
-- Table `job_search_engine`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`skill`
(
    `id` BIGINT
(
    100
) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR
(
    100
) NOT NULL,
    PRIMARY KEY
(
    `id`
)
    );

-- -----------------------------------------------------
-- Table `job_search_engine`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`user`
(
    `id` BIGINT
(
    100
) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR
(
    255
) NOT NULL,
    `password` VARCHAR
(
    255
) NOT NULL,
    PRIMARY KEY
(
    `id`
)
    );

-- -----------------------------------------------------
-- Table `job_search_engine`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`user_role`
(
    `user_id` BIGINT
(
    100
) NOT NULL,
    `role_id` BIGINT
(
    100
) NOT NULL,
    PRIMARY KEY
(
    `user_id`,
    `role_id`
),
    CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY
(
    `user_id`
)
    REFERENCES `job_search_engine`.`user`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY
(
    `role_id`
)
    REFERENCES `job_search_engine`.`role`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    );

-- -----------------------------------------------------
-- Table `job_search_engine`.`vacancy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`vacancy`
(
    `id` BIGINT
(
    100
) NOT NULL AUTO_INCREMENT,
    `position` VARCHAR
(
    100
) NOT NULL,
    `employer` VARCHAR
(
    100
) NOT NULL,
    `placement_date` TIMESTAMP NULL,
    `salary` DECIMAL
(
    10,
    2
) NOT NULL DEFAULT 0,
    `location` VARCHAR
(
    100
) NOT NULL DEFAULT 'Minsk',
    `is_deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY
(
    `id`
)
    );

-- -----------------------------------------------------
-- Table `job_search_engine`.`vacancy_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`vacancy_skill`
(
    `vacancy_id` BIGINT
(
    100
) NOT NULL,
    `skill_id` BIGINT
(
    100
) NOT NULL,
    PRIMARY KEY
(
    `vacancy_id`,
    `skill_id`
),
    CONSTRAINT `fk_vacancy_has_skill_vacancy1`
    FOREIGN KEY
(
    `vacancy_id`
)
    REFERENCES `job_search_engine`.`vacancy`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_vacancy_has_skill_skill1`
    FOREIGN KEY
(
    `skill_id`
)
    REFERENCES `job_search_engine`.`skill`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    );

-- -----------------------------------------------------
-- Table `job_search_engine`.`job_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`job_application`
(
    `id` BIGINT
(
    100
) NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT
(
    100
) NOT NULL,
    `vacancy_id` BIGINT
(
    100
) NOT NULL,
    `response_date` TIMESTAMP NULL,
    `salary` DECIMAL
(
    10,
    2
) NOT NULL DEFAULT 0,
    PRIMARY KEY
(
    `id`
),
    CONSTRAINT `fk_user_has_vacancy_user1`
    FOREIGN KEY
(
    `user_id`
)
    REFERENCES `job_search_engine`.`user`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_user_has_vacancy_vacancy1`
    FOREIGN KEY
(
    `vacancy_id`
)
    REFERENCES `job_search_engine`.`vacancy`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    );