-- MySQL Script generated by MySQL Workbench
-- Sun Mar 14 20:31:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET
@OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET
@OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET
@OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema job_search_engine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema job_search_engine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `job_search_engine` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE
`job_search_engine` ;

-- -----------------------------------------------------
-- Table `job_search_engine`.`job_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`job_application`
(
    `id` BIGINT
(
    100
) NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT
(
    100
) NOT NULL,
    `vacancy_id` BIGINT
(
    100
) NOT NULL,
    `response_date` TIMESTAMP NULL,
    `salary` DECIMAL
(
    10,
    2
) NOT NULL DEFAULT 0,
    PRIMARY KEY
(
    `id`
),
    CONSTRAINT `fk_user_has_vacancy_user1`
    FOREIGN KEY
(
    `user_id`
)
    REFERENCES `job_search_engine`.`user`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_user_has_vacancy_vacancy1`
    FOREIGN KEY
(
    `vacancy_id`
)
    REFERENCES `job_search_engine`.`vacancy`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE
INDEX `fk_user_has_vacancy_vacancy1_idx` ON `job_search_engine`.`job_application` (`vacancy_id` ASC) VISIBLE;

CREATE
INDEX `fk_user_has_vacancy_user1_idx` ON `job_search_engine`.`job_application` (`user_id` ASC) VISIBLE;

CREATE
UNIQUE INDEX `id_UNIQUE` ON `job_search_engine`.`job_application` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `job_search_engine`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`role`
(
    `id` BIGINT
(
    100
) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR
(
    255
) NOT NULL,
    PRIMARY KEY
(
    `id`
))
    ENGINE = InnoDB;

CREATE
UNIQUE INDEX `id_UNIQUE` ON `job_search_engine`.`role` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `job_search_engine`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`skill`
(
    `id` BIGINT
(
    100
) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR
(
    100
) NOT NULL,
    PRIMARY KEY
(
    `id`
))
    ENGINE = InnoDB;

CREATE
UNIQUE INDEX `id_UNIQUE` ON `job_search_engine`.`skill` (`id` ASC) VISIBLE;

CREATE
UNIQUE INDEX `name_UNIQUE` ON `job_search_engine`.`skill` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `job_search_engine`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`user`
(
    `id` BIGINT
(
    100
) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR
(
    255
) NOT NULL,
    `password` VARCHAR
(
    255
) NOT NULL,
    PRIMARY KEY
(
    `id`
))
    ENGINE = InnoDB;

CREATE
UNIQUE INDEX `iduser_UNIQUE` ON `job_search_engine`.`user` (`id` ASC) VISIBLE;

CREATE
UNIQUE INDEX `name_UNIQUE` ON `job_search_engine`.`user` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `job_search_engine`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`user_role`
(
    `user_id` BIGINT
(
    100
) NOT NULL,
    `role_id` BIGINT
(
    100
) NOT NULL,
    PRIMARY KEY
(
    `user_id`,
    `role_id`
),
    CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY
(
    `user_id`
)
    REFERENCES `job_search_engine`.`user`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY
(
    `role_id`
)
    REFERENCES `job_search_engine`.`role`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE
INDEX `fk_user_has_role_role1_idx` ON `job_search_engine`.`user_role` (`role_id` ASC) VISIBLE;

CREATE
INDEX `fk_user_has_role_user1_idx` ON `job_search_engine`.`user_role` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `job_search_engine`.`vacancy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`vacancy`
(
    `id` BIGINT
(
    100
) NOT NULL AUTO_INCREMENT,
    `position` VARCHAR
(
    100
) NOT NULL,
    `employer` VARCHAR
(
    100
) NOT NULL,
    `placement_date` TIMESTAMP NULL,
    `salary` DECIMAL
(
    10,
    2
) NOT NULL DEFAULT 0,
    `location` VARCHAR
(
    100
) NOT NULL DEFAULT 'Minsk',
    `is_deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY
(
    `id`
))
    ENGINE = InnoDB;

CREATE
UNIQUE INDEX `id_UNIQUE` ON `job_search_engine`.`vacancy` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `job_search_engine`.`vacancy_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_search_engine`.`vacancy_skill`
(
    `vacancy_id` BIGINT
(
    100
) NOT NULL,
    `skill_id` BIGINT
(
    100
) NOT NULL,
    PRIMARY KEY
(
    `vacancy_id`,
    `skill_id`
),
    CONSTRAINT `fk_vacancy_has_skill_vacancy1`
    FOREIGN KEY
(
    `vacancy_id`
)
    REFERENCES `job_search_engine`.`vacancy`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_vacancy_has_skill_skill1`
    FOREIGN KEY
(
    `skill_id`
)
    REFERENCES `job_search_engine`.`skill`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE
INDEX `fk_vacancy_has_skill_skill1_idx` ON `job_search_engine`.`vacancy_skill` (`skill_id` ASC) VISIBLE;

CREATE
INDEX `fk_vacancy_has_skill_vacancy1_idx` ON `job_search_engine`.`vacancy_skill` (`vacancy_id` ASC) VISIBLE;


SET
SQL_MODE=@OLD_SQL_MODE;
SET
FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET
UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
